name: Generate & Deploy Docs

on:
  push:
    tags:
    branches:
      - 2.x
      - 1.x
      - 0.x

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone Source Repository
        uses: actions/checkout@v3

      - name: Fetch git tags
        run: git fetch --tags origin

      - name: Clone Generated Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: fizzadar/docs.pyinfra.com
          path: docs/public/

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install
        run: |
          pip install '.[docs]'
          pip install 'jinja2<3.1'

      - name: Generate documentation
        run: scripts/build_public_docs.sh
        env:
          PYTHONPATH: '.'

      - name: Push & Update
        run: |
          cd docs/public/

          if [[ `git status --porcelain` ]]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Docs build $(date -I)"
            git push origin HEAD:main
          fi
