name: Lint & Test

on:
  push:
    branches:
      - 2.x
      - 1.x
      - 0.x
  pull_request:

jobs:
  # Linting
  #

  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install '.[test]'
      - run: flake8

  # Unit tests
  #

  unit-test:
    needs:
      - lint
    strategy:
      matrix:
        os: [ubuntu-18.04]
        python-version: [3.6, 3.7, 3.8, 3.9, "3.10"]
        include:
          - os: macos-latest
            python-version: 3.8
          - os: windows-2019
            python-version: 3.8
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install '.[test]'
      - run: pytest --cov --disable-warnings
      - uses: codecov/codecov-action@v1

  # End-to-end tests
  #

  end-to-end-test:
    needs:
      - unit-test
    strategy:
      matrix:
        os: [ubuntu-18.04]
        test-name: [local, ssh, docker]
        include:
          - os: macos-latest
            test-name: local
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install '.[test]'
      - run: pytest -m end_to_end_${{ matrix.test-name }}
